FROM node:22-slim

WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install build tools and git (Debian/Ubuntu)
RUN apt-get update && apt-get install -y build-essential python3-pip git && rm -rf /var/lib/apt/lists/*

RUN corepack enable

COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
ENV PUPPETEER_SKIP_DOWNLOAD true
