services:
  breakthrough-api:
    build: .
    container_name: breakthrough-discovery-api
    ports:
      - "8002:8000"
    volumes:
      # Mount data directory for persistent storage
      - ./data:/app/data
      - ./results:/app/results
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3